### PR TITLE
fix typos fetch docs

### PR DESCRIPTION
**Pull request by selketjah**
Fix a couple of typos in the fetch.md doc file.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Sorry @MangelMaxime. I cannot find a build target to publish the website, can you please remind me how it's done?

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I will update the repo.
It was using Fornax at first, but I get a bunch of exception when I try to run it.

I will simply convert it to our more classic way of doing thing on Fable docs. I will publish the new docs site when ready

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I pushed the new version of the docs. 

The design change a bit because it was easier and also I think it looking nicer.

Now, we can control everything from the `build.fsx` file:
- Publish / Github release: *I didn't test this ones because I had nothing to release :)*
- Docs.Watch
- Docs.Publish

I also, updated https://github.com/fable-compiler/fake-helpers/ to FAKE 5, and I created a branch fake_legacy for projects that's still need FAKE 4.

**Comment by alfonsogarciacaro** [comment]
Awesome, @MangelMaxime! Thanks a lot for this :clap: :clap:

**Pull request merged**
