### PR TITLE
Try to give better error message for fetch

### PR DESCRIPTION
**Pull request by forki**
@alfonsogarciacaro do you think this will work?

### CODE REVIEW

**Comment by MangelMaxime** [comment]
I would avoid usage of `failwithf` and any `format` in libraries because it's include a lot of JS dependencies and add significant size to the bundle.

**Comment by forki** [comment]
ok. how to rewrite? just `+` and failwith?

**Comment by MangelMaxime** [comment]
I would do that yes.

**Comment by forki** [comment]
done. 

what about the tostring on the type?

**Comment by alfonsogarciacaro** [comment]
@forki Doesn't https://github.com/fable-compiler/Fable/pull/1261 make this redundant? If you're interested in the type name we can add it to the error message you added in that PR

**Comment by forki** [comment]
no. this one adds even more context.

**Comment by MangelMaxime** [comment]
I believe `toString()` don't import the same things as `failwithf`, `sprintf`, etc.

@alfonsogarciacaro can you please confirm or infirm my statement ?

**Comment by alfonsogarciacaro** [comment]
`ToString()` [imports this function](https://github.com/fable-compiler/Fable/blob/0e4663589f4964ca787d601307fa433d7ef198e2/src/js/fable-core/Util.ts#L156-L195) which is big but it should be fine as most of Fable apps will likely use it. I wouldn't worry too much about formatting either (although I agree it's better to use `+` if you're just concatenating), before it generated a lot of code because it imported Date.ts and this imported Long.ts, which is a very big class instead of independent module functions. But I removed the Long.ts dependency from Date.ts, so you will get less code now :smile:

In any case, I still don't see how this gives more context than the new error message in `ofJson`. Sorry to be insisting but we already have three ways of fetching: `fetch`, `fetchAs` and `tryFetch` and I'm worried that it'll become confusing if each one has very different behavior, like the error management 😕

**Comment by alfonsogarciacaro** [comment]
But you will see that error (and the stack trace) with the new exception reported by `ofJson`, won't you?

**Comment by forki** [comment]
no you don't

**Comment by alfonsogarciacaro** [comment]
With Fable development version (note that I have modified the ofJson error message a bit), I've added the following tests to Fable.PowerPack.PromiseTests:

```fsharp
    it "ofJson error message" <| fun () ->
        promise { return "" }
        |> Promise.map ofJson<Foo>

    it "ofJson wrapped error message" <| fun () ->
        promise { return "" }
        |> Promise.map (fun s ->
            try
                ofJson<Foo> s
            with
            | exn -> failwith ("Could not deserialize \"" + s + "\" into type " + ((typeof<Foo>).ToString()) + ". Message: " + exn.Message))
```

When I run the tests I get:

screen shot 2017-11-27 at 2 01 54 pm

**Comment by forki** [comment]
ok. but it did not show fetchAs on my machine in the stacktrace

**Comment by alfonsogarciacaro** [comment]
@forki I'm pushing Fable 1.3.3 right now, could you please try with that? If it is still not working for you we can accept this PR 😄

**Comment by forki** [comment]
pretty sure it won't ;-)
but yes can do

**Comment by forki** [comment]
image

image

So yes no sign of fetch here

**Comment by alfonsogarciacaro** [comment]
So it's not detecting the failure? And when you use the code proposed in this PR does?

**Comment by forki** [comment]
then I'm pretty sure error message will be extended ;-)

**Comment by forki** [comment]
I'm using promise {} - it should catch right?

Am 01.12.2017 01:23 schrieb "Alfonso Garcia-Caro" <notifications@github.com

**Comment by alfonsogarciacaro** [comment]
If you've a `try ... with` **inside** the CE, yes, it should... or it's a bug of the promise CE implementation.

```fsharp
promise {
  try
     let! foo = fetchAs<Foo>()
     // Do something
  with ex ->
     // The error should be here
}
```

**Comment by forki** [comment]
but why doesn't do it with:

    promise {
      return! fetchAs<Foo>()
    }

it should still capture the exception

**Comment by alfonsogarciacaro** [comment]
Hmm, that's tricky. It's because how promises work in JS, continuations cannot access the original context. I guess is something similar why you don't catch async exceptions in F# when using `Async.Start`:

```
> let foo () =
-     async {
-         failwith "foo"
-     }
- ;;
val foo : unit -> Async<unit>

> foo() |> Async.Start;;
val it : unit = ()
```

The only thing the promise CE can do when there's an error is to call `catch` in the given promise or [return an errored promise](https://github.com/fable-compiler/fable-powerpack/blob/06593dc9bd3a1cc0a4df915b11cf37d521ed3bd7/src/Promise.fs#L124) but you still need to catch the error in order to see it. The only thing we could do is add some logging in case the user forgets to catch the exception (I think there was a discussion about this) but because we don't know the nesting level we risk writing many logs with the same error.

I think NodeJS now gives you a warning if you forget to `catch` a promise, not sure if this happens in the browser as well.

**Comment by alfonsogarciacaro** [comment]
@forki BTW, are you using Elmish? Elmish forces you to provide an error continuation when using `Cmd.ofPromise`.

**Pull request closed without merging**
