### PR TITLE
adds Custom header case

### PR DESCRIPTION
**Pull request by ed-ilyin**
Adds Custom header case.
Solves https://github.com/fable-compiler/fable-powerpack/issues/19

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks! I'll publish it right away :+1: Remember you need dotnet-fable 1.1.8 to make `Erase` union cases work properly.

**Comment by ed-ilyin** [comment]
1.1.8 version throws warning: `warning ==> /Users/ed/git/oyloo.visualstudio.com/NanoBrainsServer/src/Fable.EdIlyin.Exchange/Kraken.fs(141,58): (141,64) warning FABLE: Case Custom from Fable.PowerPack.Fetch.Fetch_types.HttpRequest
Headers is decorated with Fable.Core.EraseAttribute, but the fields are not a key-value pair
warning ==> /Users/ed/git/oyloo.visualstudio.com/NanoBrainsServer/src/Fable.EdIlyin.Exchange/Kraken.fs(142,43): (142,49) warning FABLE: Case Custom from Fable.PowerPack.Fetch.Fetch_types.HttpRequest
Headers is decorated with Fable.Core.EraseAttribute, but the fields are not a key-value pair`

**Comment by alfonsogarciacaro** [comment]
@ed-ilyin Can you post your code? You should use a string literal plus a value, unfortunately it doesn't work with string references (I should have add it to the warning).

**Comment by ed-ilyin** [comment]
my code looks like this:
```
        let headers =
            [   ContentType "application/x-www-form-urlencoded"
                "API-Key" => Json.Encode.string apiKey |> Custom
                "API-Sign" => signature |> Custom
            ]
```

**Comment by ed-ilyin** [comment]
I changed code to this:
```
        let headers =
            [   ContentType "application/x-www-form-urlencoded"
                Custom ("API-Key", Json.Encode.string apiKey)
                Custom ("API-Sign", signature)
            ]
```
and now problem is gone
thank you

**Pull request merged**
