### PR TITLE
Add Promise.catchBind, change signature of Promise.either to allow for returning either value or promise.

### LINKED ISSUE #23: `Promise` doesn't provide variants of `catch` and `either` where the rejection function returns another `Promise`
According to the [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.prototype.catch), `Promise.catch(f)` is sugar for `Promise.then(id, f)`, which allows `f : exn -> U2<'T, Promise<'T>>`, whereas the Fable.PowerPack's current implementations only allow `f : exn -> 'T`.

To avoid breaking changes, I propose not to change the signatures of `catch` and `either`, but add two new functions, `catchBind` and `eitherBind` respectively:

```
[<Emit("$1.catch($0)")>]
let catchBind (a: Exception->Promise<'T>) (pr: JS.Promise<'T>): JS.Promise<'T> = jsNative

[<Emit("$2.then($0,$1)")>]
let eitherBind (success: 'T->'R) (fail: Exception->Promise<'R>) (pr: JS.Promise<'T>): JS.Promise<'R> = jsNative
```

(I'm not completely sure about the names - not a native English speaker myself - so if anyone has better ideas...)

### PR DESCRIPTION
**Pull request by fsoikin**
Fixes #23.

### CODE REVIEW

**Comment by fsoikin** [comment]
@alfonsogarciacaro question: should I update `RELEASE_NOTED.md` myself, or do you just dump commit messages there when it's time to release?

**Comment by alfonsogarciacaro** [comment]
Great, thanks!

Yeah, updating RELEASE_NOTES is not automated at the moment, so you can update it with the PR. But don't worry I can do it this time :+1:

**Comment by fsoikin** [comment]
Oh, I already created a PR. :-)

**Comment by alfonsogarciacaro** [comment]
Hehe, you were faster than me. That's ok too, thanks a lot! 🥇

**Pull request merged**
