### PR TITLE
Date.Local Russian localization

### PR DESCRIPTION
**Pull request by irium**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Good one, thank you! I totally forgot this module was in Fable.PowerPack 😅  @forki wanted something like this for German, I think. @MangelMaxime can this also be used to parse dates in different languages?

**Comment by alfonsogarciacaro** [comment]
Published as 1.3.4 :+1:

**Comment by irium** [comment]
Wow, you so fast! :)

I think that this potentially could grow into a lot of code, so when/if a lot of languages will be added it will require to be split up into separate lib :)

**Comment by alfonsogarciacaro** [comment]
Yes, that makes sense. Though hopefully right now in normal apps the Date file won't get into the bundle if you don't reference it and when you do it (also hopefully) tree shaking should remove the values you're not using.

**Comment by irium** [comment]
Ahh! That makes sense too :) I completely forgot, that Fable does not depend of binary dll distribution size :)

**Pull request merged**
