### PR TITLE
Adding in safe statically-typed JSON parser

### PR DESCRIPTION
**Pull request by Pauan**
dotnet still isn't working for me, so I'm not able to test it, but it probably works (?!)

It could also use some unit tests, but I can't test those either.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Interesting, thank you!

BTW, what problems do you have with dotnet? Which dotnet SDK and OS are you using?

**Comment by Pauan** [comment]
I'm using the latest version of the dotnet SDK (1.0.1)

Basically, there's a [bug in dotnet which causes a `Segmentation fault` on Debian Testing/Unstable](https://github.com/dotnet/core-setup/issues/545).

**Comment by aolney** [comment]
Sorry to contaminate this issue, but I found it through Pauan's reference. Here's what I did to fix dotnet on Debian unstable

- Modified the [install script](https://gist.github.com/aolney/8d951cc15692e772e0ace8e27800555a) to handle Debian 9 and a bash shell
- After it runs do `find /opt/dotnet -name '*.so' -type f -print | xargs ldd | grep 'not found'` to see if you are missing any libraries
- For me, it was `liblldb.so`. I installed `liblldb-3.7` and then linked the library to `/usr/lib/x86_64-linux-gnu/liblldb.so`
- Even after this, `dotnet restore` would segfault, apparently [because dotnet depends on old versions of libcurl3](https://github.com/dotnet/core-setup/issues/545)
- Resolved by [adding stable.list to sources.list.d](https://serverfault.com/questions/22414/how-can-i-run-debian-stable-but-install-some-packages-from-testing), running `apt-get update`, and then running `apt-get install libcurl3=7.38.0-4+deb8u5 libcurl4-openssl-dev=7.38.0-4+deb8u5`

**Comment by alfonsogarciacaro** [comment]
Hi @aolney, thanks a lot for the info! I think @Pauan fixed it doing something similar. It can be helpful to add the information also in https://github.com/dotnet/core-setup/issues/545 to help other dotnet users with the same problem, what do you think?

**Comment by Pauan** [comment]
@aolney Thanks for the info, but in my case all I needed to do was install the Stable version of `libcurl3`. But I'm on Testing, so maybe Unstable needs your additional steps.

**Comment by aolney** [comment]
I'll post as @alfonsogarciacaro suggests now

**Comment by aolney** [comment]
FWIW an unstable update broke this again, so I created [a docker image](https://hub.docker.com/r/aolney/fable-dotnet-104/)

**Pull request merged**
