### PR TITLE
Fix fetchAs

### PR DESCRIPTION
**Pull request by forki**
/cc @MangelMaxime @tforkmann

### CODE REVIEW

**Comment by forki** [comment]
the problem was that .json is already converting the string to an js object and then thoth autodecoder is going nuts.

**Comment by tforkmann** [comment]
nice one!

**Comment by MangelMaxime** [comment]
Looks good, will add some tests using [randomuser](https://randomuser.me/) to be sure it's working this time.

It's what we are using for the `Thoth / Elmish / Fetch` example in the REPL.

**Comment by MangelMaxime** [comment]
Released in 2.0.2

**Pull request merged**
